algo = input('Digite algo: ')
print(f'O tipo primitivo do que foi digitado é {type(algo)}')
print(f'Só tem espaços? {algo.isspace()}')
print(f'É um número ? {algo.isnumeric()}')
print(f'É alfabético ? {algo.isalpha()}')
print(f'É alfanúmerico ? {algo.isalpha()}')
print(f'Está em maiúsculas? {algo.isupper()}')
print(f'Está em minúsculas? {algo.islower()}')
print(f'Está capitálizada? {algo.istitle()}')
